# Generated by Django 3.0.3 on 2020-06-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.IntegerField()),
                ('available_since', models.CharField(max_length=20)),
                ('roles', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Agents',
            },
        ),
    ]
